### ISSUE TITLE
ヘッダー要素のアルファベットを大文字ではなく原文ママにしたい

### ISSUE THREAD

**Issue by ftnext** [ftnext/2021_slides#6]
デフォルトではヘッダーのアルファベットが大文字で表示されてしまう

GitPitchでも設定した件（ヘッダーの`text-transform`プロパティ）
https://github.com/ftnext/CogBot11-LT-201801/issues/2#issuecomment-359235919

**Comment by ftnext** [comment]
## Workaround
`make revealjs` してできるHTMLファイルのheadタグ内に以下を書き込んだ

```html
  <head>
  <style>
    .reveal h1, .reveal h2, .reveal h3, .reveal h4, .reveal h5, .reveal h6 {
      text-transform: none;
    }
  </style>

  </head>
```

ref: https://github.com/hakimel/reveal.js/issues/2226#issuecomment-423818041

ビルドするたびに手動で追加が必要になっている。
恒久対応として、conf.pyの設定からビルドしたHTMLのheadタグの中にstyleが書かれたらよさそう

**Comment by attakei** [comment]
複数のスライドで恒久的に `text-transform: none` にしたいのであれば、`source/_static`配下にCSSファイルを用意した上で、`revealjs_css_files` で指定するのが楽だと思います。

- [ドキュメント](https://sphinx-revealjs.readthedocs.io/en/latest/configurations.html#revealjs-css-files)
- [実際の利用例 ※ちょっと特殊ですが](https://gitlab.com/attakei.net/slides/pyconjp-2020/)

**Comment by ftnext** [comment]
@attakei 教えてくださりありがとうございます。
教わった方法で`source/_static`配下のCSS（☆）をスライドのHTMLのlinkタグに加えられました。
ところが、（☆）のCSSの後に、テーマのCSSが適用されるという順番のために、スライドに`text-transform: none`が適用されませんでした

```HTML
    <link rel="stylesheet" type="text/css" href="../_static/css/common.css" />
    <link rel="stylesheet" href="../_static/revealjs4/dist/theme/black.css" type="text/css" />
```

HTMLを編集して、この2つの順番を逆にすると、（☆）のCSSの`text-transform: none`が適用されます。

この件についてIssueとPull requestを上げますので、ご確認いただけますとありがたいです。

**Comment by attakei** [comment]
`sphinx-revealjs`の方へのフィードバックありがとうございました。
先程PR取り込んでv1.0.1をPyPIに公開しました。手元のビルドでもテーマ用のCSSが先に出るようになっているため、問題の解消が出来たかと思います。

**Comment by ftnext** [comment]
@attakei PR取り込んでいただきありがとうございます。
v1.0.1にupgradeしてビルドしたところ、テーマ用のCSSが先に出て、問題は解消されました😃
